FROM node:18-alpine AS build
WORKDIR /app

COPY lib-client/package.json lib-client/package-lock.json ./
RUN npm install

COPY lib-client/ ./
RUN npm run build -- --configuration production

FROM nginx:alpine
COPY --from=build /app/dist/lib-client /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"] 